branch-defaults:
  develop:
    environment: Turtle-Tracking-dev
    group_suffix: null
global:
  application_name: Turtle-Tracking
  branch: develop
  default_ec2_keyname: your-key-pair-name
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
