branch-defaults:
  develop:
    environment: dash-env
    group_suffix: null
environment-defaults:
  dash-env:
    branch: null
    repository: null
global:
  application_name: dash-app
  branch: null
  default_ec2_keyname: AKIAYDWHTIBGI73GXNOY
  default_platform: Python 3.11
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
