name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - develop   # Trigger on push to the main branch
  pull_request:
    branches:
      - main   # Trigger on PR to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'  # Choose your AWS region

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create Elastic Beanstalk environment (if not created already)
      - name: Create Elastic Beanstalk Environment
        run: |
          eb init -p python-3.7 my-dash-app --region eu-central-1  # Replace with your app name
          eb create my-dash-app-env --region eu-central-1  # Replace with your environment name

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy --region eu-central-1
          eb open  # Optionally open the URL after deployment

